### ISSUE TITLE
Expected identifier, string or number

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning-CLI#1]
In Edge, not in Chrome, I get this error in console:
```
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
appBundle.js (332,23)
```
The code:

```
const errorMetric = (type, message, code, visible, params = {}) => {
	  params = { params, ...{ message, code, visible } }; // This line
	  sendMetric(type, 'error', params);
	};
```
So the app currently not working in Edge.

**Comment by michielvandergeest** [comment]
It seem that Edge doesn't handle spread operator correctly, which is causing the error.
Since Edge is currently not one of our target browser, I don't expect we'll be making Edge specific fixes atm. 

Please note that Es5-support is in the works. An Es5 version could possibly be used to run in Edge.
